import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { Marked } from 'marked';

const root = process.cwd();
const contentRoot = path.join(root, 'content');
const outputFile = path.join(root, 'site', 'data', 'content.js');
const assetOutput = path.join(root, 'site', 'media', 'content');

fs.rmSync(assetOutput, { recursive: true, force: true });
fs.mkdirSync(assetOutput, { recursive: true });

const escapeHtml = value => String(value).replace(/[&<>'"]/g, character => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
})[character]);

function publicPath(relativePath) {
  return relativePath.split(path.sep).map(encodeURIComponent).join('/');
}

function publishAsset(href, sourceFile) {
  if (!href || /^(?:[a-z]+:|#|\/)/i.test(href)) return href;
  const cleanHref = decodeURIComponent(href.split(/[?#]/, 1)[0]);
  const source = path.resolve(path.dirname(sourceFile), cleanHref);
  const relative = path.relative(contentRoot, source);
  if (relative.startsWith('..') || path.isAbsolute(relative)) throw new Error(`Asset must stay inside content/: ${href}`);
  if (!fs.existsSync(source) || !fs.statSync(source).isFile()) throw new Error(`Missing asset in ${path.relative(root, sourceFile)}: ${href}`);
  const destination = path.join(assetOutput, relative);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.copyFileSync(source, destination);
  return `media/content/${publicPath(relative)}`;
}

function parserFor(sourceFile) {
  const parser = new Marked();
  parser.use({
    renderer: {
      image(token) {
        const src = publishAsset(token.href, sourceFile);
        const title = token.title ? ` title="${escapeHtml(token.title)}"` : '';
        return `<img src="${escapeHtml(src)}" alt="${escapeHtml(token.text)}"${title} loading="lazy">`;
      }
    }
  });
  return parser;
}

function normalizeDate(value, file) {
  const date = value instanceof Date ? value.toISOString().slice(0, 10) : String(value || '');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error(`Invalid date in ${path.relative(root, file)}: ${date}`);
  return date.replaceAll('-', '.');
}

function coverFrom(data, file) {
  if (!data.cover) return null;
  return {
    src: publishAsset(String(data.cover), file),
    alt: String(data.coverAlt || ''),
    position: String(data.coverPosition || '50% 50%')
  };
}

function markdownFiles(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory)
    .filter(name => name.endsWith('.md'))
    .map(name => path.join(directory, name));
}

function readArticle(file) {
  const parsed = matter(fs.readFileSync(file, 'utf8'));
  if (parsed.data.draft === true) return null;
  const slug = String(parsed.data.slug || path.basename(file, '.md')).replace(/^\d{4}-\d{2}-\d{2}-/, '');
  if (!/^[a-z0-9-]+$/.test(slug)) throw new Error(`Invalid slug in ${path.relative(root, file)}: ${slug}`);
  const parser = parserFor(file);
  return {
    slug,
    title: String(parsed.data.title || '').trim(),
    category: String(parsed.data.category || '未分类').trim(),
    date: normalizeDate(parsed.data.date, file),
    excerpt: String(parsed.data.excerpt || '').trim(),
    body: parser.parse(parsed.content).trim()
  };
}

function readNote(file) {
  const parsed = matter(fs.readFileSync(file, 'utf8'));
  if (parsed.data.draft === true) return null;
  const parser = parserFor(file);
  return {
    date: normalizeDate(parsed.data.date, file),
    time: String(parsed.data.time || '00:00'),
    context: String(parsed.data.context || '').trim(),
    html: parser.parseInline(parsed.content.trim())
  };
}

const aboutFile = path.join(contentRoot, 'about.md');
const aboutParsed = matter(fs.readFileSync(aboutFile, 'utf8'));
const aboutParser = parserFor(aboutFile);
const about = {
  slug: 'about-me',
  title: String(aboutParsed.data.title || '关于我'),
  category: String(aboutParsed.data.category || '关于'),
  date: normalizeDate(aboutParsed.data.date, aboutFile),
  excerpt: String(aboutParsed.data.excerpt || ''),
  cover: coverFrom(aboutParsed.data, aboutFile),
  body: aboutParser.parse(aboutParsed.content).trim()
};

const posts = markdownFiles(path.join(contentRoot, 'posts')).map(readArticle).filter(Boolean)
  .sort((a, b) => b.date.localeCompare(a.date));
const notes = markdownFiles(path.join(contentRoot, 'notes')).map(readNote).filter(Boolean)
  .sort((a, b) => `${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`));

for (const article of [about, ...posts]) {
  if (!article.title || !article.excerpt || !article.body) throw new Error(`Article ${article.slug} is missing title, excerpt, or body`);
}

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
const generated = `// Generated by tools/build-content.mjs. Edit files in content/ instead.\nexport const about = ${JSON.stringify(about, null, 2)};\n\nexport const notes = ${JSON.stringify(notes, null, 2)};\n\nexport const posts = ${JSON.stringify(posts, null, 2)};\n`;
fs.writeFileSync(outputFile, generated, 'utf8');
console.log(`Built ${posts.length} articles, ${notes.length} notes, and the about page.`);
